### ISSUE TITLE
Add Boyer-Moore algorithm

### ISSUE THREAD

**Issue by marisvali** [marisvali/azharja#1]
# Description

Azharja is missing search functionalities. The first step in adding a search functionality is to have a fast algorithm for searching a substring in a string.

# Acceptance criteria

- There is an implementation of the Boyer-Moore algorithm that works with QStrings.
- There is a function that returns all occurrences of a string found in the mAnswer and mJournal strings from all the Item objects in MainWindow::mData.

# Tasks

- [x] Make a message box appear when pressing Ctrl + f.
- [x] Make a message box appear when pressing Ctrl + f that shows how many times the word "ceva" appers in all the .txt files in Data/Items.
- [x] Make a dialog appear when pressing Ctrl + f, with an Ok and a Cancel button.
- [x] Make a dialog appear when pressing Ctrl + f, with a text box, an Ok and a Cancel button. When you press ok, search for the string in the text box and have a message box appear with how many times the word appeared in the .txt files in Data/Items.
- [x] Search in MainWindow::mData instead of the files.
  - [x] Read the Data class and understand how it works. Notice that it's a class that only has the role of managing data. It has no UI elements, no QWidget anywhere. It is a collection of Item objects, where an Item object contains the data read from disk for an item. An item has a need (title), an answer and a journal. You want to search the answer and journal strings. You don't have to understand the threading part yet (mutexes etc).
  - [x] Read the Item class and understand how it works.
  - [x] Read how objects of type Item and Data are used in the project. Who does what with them?
  - [x] Do the search on strings, not in files.
- [x] Implement the Boyer-Moore algorithm and use it to do the search instead of QString::indexOf.
  - [x] Copy-paste existing implementation in the .cpp where you need it.
  - [x] Adapt it to use QStrings.
  - [x] Create appropriate .h and .cpp files for it.
  - [x] Adapt the code to match the coding style in the rest of Azharja.
